-- Copy and paste this into the Supabase SQL Editor to create the internships table

CREATE TABLE IF NOT EXISTS internships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  required_skills TEXT[] NOT NULL,
  preferred_skills TEXT[] NOT NULL,
  location TEXT NOT NULL,
  stipend TEXT NOT NULL,
  description TEXT NOT NULL,
  apply_link TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) but allow anonymous reads/writes for this project
ALTER TABLE internships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous select" ON internships
  FOR SELECT TO anon
  USING (true);

CREATE POLICY "Allow anonymous insert" ON internships
  FOR INSERT TO anon
  WITH CHECK (true);

CREATE POLICY "Allow anonymous delete" ON internships
  FOR DELETE TO anon
  USING (true);
